# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: requirements-txt-fixer
    -   id: check-ast
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys, --indent=4]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3
    hooks:
    -   id: pycln
